[package]
name = "aoc2019"
version = "0.1.0"
edition = "2021"
authors = ["Aurélien Geron <ageron@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
regex = "1.6.0"
pathfinding = "3.0.14"
